// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqrsphjgsrdfwxilscog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxcnNwaGpnc3JkZnd4aWxzY29nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NzI2MzMsImV4cCI6MjA2NjQ0ODYzM30.MOkq7dgYMEhqIycpXil0l3O6_vQ3ZcMmAAu-OHevN10";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);